### ISSUE TITLE
Cannot download Visuelle2.0 data

### ISSUE THREAD

**Issue by yaoyang33** [HumaticsLAB/visuelle2.0-code#4]
Hi can you double check the visuelle2.0 datset link? It shows 'unable to establish ssl connection'

Thanks!

**Comment by geriskenderi** [comment]
Hi, I answered your question by e-mail, but I'm just leaving this here in case anyone else is running into the same problem. 

The link is working, the problem is that if you wish to download the dataset directly into a remote machine, you cannot use wget in a direct and simple manner with Mega.nz (Similarly to Google Drive and other hosting services). 

For Linux and Windows, the following tool is available: https://megatools.megous.com/

In case you cannot get the tool to work, you have to download the dataset first into a machine where you have a GUI available and then upload it into your server. I understand that this is not very efficient, but VISUELLE2.0 is not an extremely large dataset in terms of memory (~2GB) so with a stable connection even this last step should take no more than 30-40mins
